Bump kubernetes.core version to v2.3.2
ansible/awx-resource-operator pull request #74
Opened 2022-08-16 03:58 UTC by rooftopcellist

Bump kubernetes.core collection version from v1.2.1 to v2.3.2 to match the awx-operator and pulp-operator.  

We need to test ansiblejob and jobtemplate functionality before merging this.

2022-08-16 15:31 UTC, dsavineau requested changes

2022-08-16 15:31 UTC, dsavineau commented on .github/workflows/ci.yaml
> +         ansible-galaxy collection install community.general kubernetes.core:2.3.2 operator_sdk.util
I guess the `community.general` collection was added for the `docker_image` module but it's not present in the general collection since 2.0.0 so you'll need to use the community.docker collection instead
```suggestion
         ansible-galaxy collection install -r requirements.yml
         ansible-galaxy collection install community.docker
```

2022-08-22 13:33 UTC, dsavineau approved these changes

2022-08-22 13:52 UTC, merged

2022-08-22 13:53 UTC, rooftopcellist commented
Molecule tests are now passing.  I commented out the integration tests for now because they will fail until we find a good way to stand up awx within our github workflow to test against.  This can be covered in a later work item.